version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /griffon/pkg/test-fixtures/image-simple
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /griffon/pkg/test-fixtures/image-simple
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /griffon/pkg/test-fixtures/image-simple/target/nested
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /griffon/presenter/json/test-fixtures/image-simple
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /griffon/presenter/sarif/test-fixtures/image-simple
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /test/cli/test-fixtures/image-bare
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /test/cli/test-fixtures/image-java-subprocess
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /test/cli/test-fixtures/image-node-subprocess
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /test/integration/test-fixtures/image-alpine-match-coverage
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /test/integration/test-fixtures/image-arch-match-coverage
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /test/integration/test-fixtures/image-centos-match-coverage
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /test/integration/test-fixtures/image-debian-match-coverage
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /test/integration/test-fixtures/image-debian-match-coverage/golang
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /test/integration/test-fixtures/image-debian-match-coverage/javascript/pkg-json
    schedule:
      interval: daily

  - package-ecosystem: bundler
    directory: /test/integration/test-fixtures/image-debian-match-coverage/ruby
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /test/integration/test-fixtures/image-portage-match-coverage
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /test/integration/test-fixtures/image-sles-match-coverage
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /test/quality
    schedule:
      interval: daily
